contracts/POA20.sol, contracts/libraries/Helpers.sol, contracts/upgradeable_contracts/Ownable.sol, contracts/upgradeable_contracts/U_BridgeValidators.sol, contracts/upgradeable_contracts/U_ForeignBridge.sol, contracts/upgradeable_contracts/U_HomeBridge.sol, flats/BridgeValidators_flat.sol, flats/ForeignBridge_flat.sol, flats/HomeBridge_flat.sol, flats/POA20_flat.sol
1. Remove unused PausableToken from POA20
2. Small enhancements like removing dublicated checks
=> Audit team1 feedback

contracts/POA20.sol, contracts/upgradeable_contracts/U_BridgeValidators.sol, contracts/upgradeable_contracts/U_ForeignBridge.sol, contracts/upgradeable_contracts/U_HomeBridge.sol, flats/BridgeValidators_flat.sol, flats/ForeignBridge_flat.sol, flats/HomeBridge_flat.sol, flats/POA20_flat.sol, test/foreign_bridge_test.js, test/home_bridge_test.js, test/poa20_test.js, test/validators_test.js
1. remove finishMinting
2. Fix transferAndCall
=> Audit feedback: POA20

contracts/IBurnableMintableERC677Token.sol, contracts/POA20.sol, contracts/upgradeable_contracts/U_ForeignBridge.sol, flats/ForeignBridge_flat.sol, flats/POA20_flat.sol, migrations/3_upgradeable_deployment.js, test/foreign_bridge_test.js, test/poa20_test.js, test/testContracts/ForeignBridgeV2.sol
allow owners to withdraw accidentally sent token to their senders.
=> add claimTokens func to POA20 and ForeignBridge

contracts/ERC677.sol, contracts/ERC677Receiver.sol, contracts/IBridgeValidators.sol, contracts/IBurnableMintableERC677Token.sol, contracts/Migrations.sol, contracts/POA20.sol, contracts/libraries/Message.sol, contracts/libraries/SafeMath.sol, contracts/upgradeability/EternalStorage.sol, contracts/upgradeability/EternalStorageProxy.sol, contracts/upgradeability/OwnedUpgradeabilityProxy.sol, contracts/upgradeability/Proxy.sol, contracts/upgradeability/UpgradeabilityOwnerStorage.sol, contracts/upgradeability/UpgradeabilityProxy.sol, contracts/upgradeability/UpgradeabilityStorage.sol, contracts/upgradeable_contracts/Ownable.sol, contracts/upgradeable_contracts/U_BasicBridge.sol, contracts/upgradeable_contracts/U_BridgeValidators.sol, contracts/upgradeable_contracts/U_ForeignBridge.sol, contracts/upgradeable_contracts/U_HomeBridge.sol, deploy/src/deploymentUtils.js, deploy/src/foreign.js, deploy/src/home.js, package-lock.json, package.json, truffle.js
provide 0.4.23 version for all contracts bump and enable optimization
=> 0.4.23 bump and deployment logging optimization

contracts/libraries/Message.sol, contracts/upgradeable_contracts/U_HomeBridge.sol
=> Clean up V2

contracts/upgradeable_contracts/U_HomeBridge.sol
Fix if receiver is a contract that doesn't have payable fallback
=> apply patch to prevent an attack on home

contracts/upgradeable_contracts/BridgeValidators.sol, test/validators_test.js
This PR includes recent changes added to `v2` branch so that functionality can be used on v2.1 contract version.
- Add deployedAtBlock on BridgeValidators from #54 
- Add index on validator events #49
=> Update BridgeValidators contract

README.md, deploy/README.md
The main README and deployment README are updated
=> Documentation updates before release

contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, deploy/src/erc_to_erc/foreign.js, test/erc_to_erc/foreign_bridge.test.js, test/setup.js
=> Add gas price on initialization of Foreign erc-to-erc mode

contracts/upgradeable_contracts/ERC677Bridge.sol, contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol, contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol, contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol, test/erc_to_erc/foreign_bridge.test.js, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/foreign_bridge.test.js, test/erc_to_native/home_bridge.test.js, test/native_to_erc/foreign_bridge_test.js, test/native_to_erc/home_bridge_test.js
Add a check on initialization to verify that validator and token addresses are contract addresses.
Closes #96
=> Add validator and token contract address check 

deploy/deploy.js, deploy/src/erc_to_erc/foreign.js, deploy/src/erc_to_erc/home.js, deploy/src/erc_to_native/foreign.js, deploy/src/erc_to_native/home.js, deploy/src/native_to_erc/foreign.js, deploy/src/native_to_erc/home.js
`bridgeDeploymentResults.json` unified for all bridge modes:
* `NATIVE-TO-ERC`
```json
{   
"homeBridge": {
"address": "0xdbe9edFe31C3b9A3584c28f4a774dcD905543A27",
"deployedBlockNumber": 5435393
},
"foreignBridge": {
"address": "0x22EAdAa672DF3228911ad28327074A40B2113656",
"deployedBlockNumber": 5435404,
"erc677": {
"address": "0xb97fAD8238f20BC653f67DC4D91D7e66f2753fFb"
}
}
}
```
* `ERC-TO-ERC`
```json
{
"homeBridge": {
"address": "0x5DF96472cc24836f0845ba0Eb882b6Eb90a41582",
"deployedBlockNumber": 5436542,
"erc677": {
"address": "0x66CFD053740DE673194E335083c7243cac8Fa76A"
}
},
"foreignBridge": {
"address": "0xC5125f36F95627402A3938a2125013E7405edC4c",
"deployedBlockNumber": 5436560
}
}
```
* `ERC-TO-NATIVE`
```json
{
"homeBridge": {
"address": …
```
=> Unification for bridgeDeploymentResults.json

contracts/upgradeable_contracts/U_ForeignBridge.sol, contracts/upgradeable_contracts/U_HomeBridge.sol, deploy/src/foreign.js, deploy/src/home.js, migrations/3_upgradeable_deployment.js, test/foreign_bridge_test.js, test/home_bridge_test.js
Relates to issue #108
Gist for deployed HomeBridge: https://gist.github.com/patitonar/df585134034f5b6fbe01928fc6e00e36
Gist for deployed ForeignBridge: https://gist.github.com/patitonar/0ff940d070ef5c4d3dbd70e44eeae361
=> Extend Native-ERC20 limits functionality on contracts v1.1

README.md, REWARD_MANAGEMENT.md
Add reward management file with details on how fees are distributed for `NATIVE-TO-ERC` and `ERC-TO-NATIVE`
=> Add reward management schemes

contracts/upgradeable_contracts/BaseFeeManager.sol, contracts/upgradeable_contracts/RewardableBridge.sol, contracts/upgradeable_contracts/erc20_to_native/FeeManagerErcToNative.sol, contracts/upgradeable_contracts/native_to_erc20/FeeManagerNativeToErc.sol, test/erc_to_native/home_bridge.test.js, test/native_to_erc/foreign_bridge_test.js, test/native_to_erc/home_bridge_test.js
=> Add fee manager mode interface

contracts/upgradeable_contracts/BaseBridgeValidators.sol, contracts/upgradeable_contracts/RewardableValidators.sol, test/validators_test.js
See this comment https://github.com/poanetwork/bridge-ui/pull/184#discussion_r274128161
=> Add validatorList on BaseBridgeValidators

contracts/upgradeable_contracts/BasicHomeBridge.sol, contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol, contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol, test/erc_to_native/home_bridge.test.js, test/native_to_erc/home_bridge_test.js
=> Emit event on fee distribution from transfer

contracts/upgradeable_contracts/BaseBridgeValidators.sol, contracts/upgradeable_contracts/BridgeValidators.sol, contracts/upgradeable_contracts/RewardableValidators.sol, test/rewardable_validators_test.js
=> Update RewardableValidators to be compatible with BridgeValidators  

deploy/package-lock.json
When trying to install dependencies from `deploy` the following error was present:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/web3-providers-ws/websocket@git:/github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2" as it does not contain a package.json file.
```
To fix this, the solution was to regenerate `package-lock.json`
=> Fix deploy/package-lock.json

contracts/IBlockReward.sol, contracts/test/BlockReward.sol, contracts/upgradeable_contracts/erc20_to_erc20/FeeManagerErcToErcPOSDAO.sol, contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/home_bridge.test.js, test/testContracts/oldBlockReward.sol
=> Update setBlockRewardContract method validations

contracts/upgradeable_contracts/BaseFeeManager.sol, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/home_bridge.test.js, test/native_to_erc/foreign_bridge_test.js, test/native_to_erc/home_bridge_test.js
=> Add fee value check

contracts/upgradeable_contracts/OverdrawManagement.sol, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/home_bridge.test.js
=> Fix fixAssetsAboveLimits imbalance when feeManager enabled

contracts/ERC677BridgeToken.sol, test/poa20_test.js
=> Update ERC677BridgeToken transferFrom to call contractFallback

contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
=> Remove redundant fallback method on HomeBridgeErcToErc

contracts/libraries/Message.sol
=> Remove address mask in parseMessage

deploy/deploy.js, deploy/src/deploymentUtils.js, deploy/src/erc_to_erc/preDeploy.js, deploy/src/erc_to_native/preDeploy.js, deploy/src/loadEnv.js, deploy/src/native_to_erc/preDeploy.js
Closes #185 
Refactored `loadEnv.js` so now:
- First we check that all required parameters are present and in the correct type
- Then we check that the values assigned to the parameters makes sense in order to comply with the requires of the contracts.
Added `preDeploy` checks on the deployment script, to verify that the contracts addresses provided on the parameters have code.
=> Improve checks of configuration parameters for contracts deployment

contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol, deploy/src/loadEnv.js, test/erc_to_erc/home_bridge.test.js
=> Support zero fallback gas price in erc-to-erc mode

contracts/ERC677BridgeToken.sol, contracts/libraries/Message.sol, contracts/upgradeable_contracts/BaseBridgeValidators.sol
=> Improve revert pattern

contracts/upgradeable_contracts/BaseBridgeValidators.sol, contracts/upgradeable_contracts/BridgeValidators.sol, contracts/upgradeable_contracts/RewardableValidators.sol, test/helpers/helpers.js, test/rewardable_validators_test.js, test/validators_test.js
=> Add validators amount limit

package-lock.json, package.json
Update project version related to changes in https://github.com/poanetwork/poa-bridge-contracts/pull/248
=> Update project version to v2.3.3

contracts/upgradeable_contracts/BasicBridge.sol, contracts/upgradeable_contracts/OverdrawManagement.sol, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/home_bridge.test.js
=> Allow fixAssetsAboveLimits to fix partial amounts

package-lock.json, package.json
Update project version related to changes in #266
=> Update project version to v2.4.0

deploy/src/erc_to_erc/home.js, deploy/src/erc_to_native/home.js, deploy/src/loadEnv.js, deploy/src/native_to_erc/foreign.js, deploy/src/native_to_erc/home.js
=> Process validator's reward accounts only when used in deploy script

contracts/upgradeable_contracts/BasicBridge.sol, contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErc677ToErc677.sol, contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErcPOSDAO.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol, contracts/upgradeable_contracts/native_to_erc20/ClassicHomeBridgeNativeToErc.sol, contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol, contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol, deploy/.env.example, deploy/src/erc_to_erc/foreign.js, deploy/src/erc_to_erc/home.js, deploy/src/erc_to_native/foreign.js, deploy/src/erc_to_native/home.js, deploy/src/native_to_erc/foreign.js, deploy/src/native_to_erc/home.js, test/erc_to_erc/foreign_bridge.test.js, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/foreign_bridge.test.js, test/erc_to_native/home_bridge.test.js, test/native_to_erc/foreign_bridge_test.js, test/native_to_erc/home_bridge_test.js, test/poa20_test.js
Implementation proposal for decimal shift feature issue #243
=> decimal shift feature 

deploy/package-lock.json, package-lock.json, package.json
Closes #275 
Updated main and `deploy` dependencies using `npm audit` tool.
=> Update project dependencies

package-lock.json, package.json
Update project version related to changes in #277 
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/204.
=> Update project version to v3.0.0

package-lock.json, package.json
Update project version related to changes in #285 
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/214
=> Bump version to 3.1.0

contracts/upgradeable_contracts/BaseBridgeValidators.sol, contracts/upgradeable_contracts/BasicBridge.sol, contracts/upgradeable_contracts/Initializable.sol, contracts/upgradeable_contracts/InitializableBridge.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol, test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js
=> Remove deployed at block information in mediators contracts

.solhint.json, contracts/upgradeable_contracts/ERC20Bridge.sol, contracts/upgradeable_contracts/InitializableBridge.sol, contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErc677ToErc677.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol, deploy/deploy.js, deploy/src/erc_to_native/foreign.js, deploy/src/loadEnv.js, test/erc_to_native/foreign_bridge.test.js, test/erc_to_native/home_bridge.test.js
=> Add alternative receiver for transfer in erc20 to native mode

contracts/libraries/Bytes.sol, contracts/upgradeable_contracts/BaseERC677Bridge.sol, contracts/upgradeable_contracts/ERC677Bridge.sol, contracts/upgradeable_contracts/ERC677BridgeForBurnableMintableToken.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/ForeignAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/HomeAMBErc677ToErc677.sol, test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js, test/amb_erc677_to_erc677/foreign_bridge.test.js, test/amb_erc677_to_erc677/home_bridge.test.js
=> Add alternative receiver for ERC677-to-ERC677 on top of AMB

contracts/ERC677BridgeToken.sol, contracts/upgradeable_contracts/VersionableBridge.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol
=> Update interfaces version

.gitignore, package-lock.json, package.json
Update project version related to changes in #315
The changes have been verified under poanetwork/tokenbridge#228
=> Bump version to 3.2.0

contracts/ERC677BridgeToken.sol, contracts/interfaces/ERC677.sol, test/poa20_test.js
=> Possibility of increasing/decreasing allowance in ERC677

package-lock.json, package.json
Update project version related to changes in #341 
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/247
=> Bump version to 3.3.0-rc0

package-lock.json, package.json
Update project version related to changes in #345 
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/258.
=> Bump version to 3.3.0

contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol
=> Fixed minimum gas usage estimation

contracts/libraries/Message.sol, contracts/upgradeable_contracts/BasicForeignBridge.sol, contracts/upgradeable_contracts/VersionableBridge.sol, contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol, test/arbitrary_message/foreign_bridge.test.js, test/erc_to_erc/foreign_bridge.test.js, test/erc_to_native/foreign_bridge.test.js, test/helpers/helpers.js, test/native_to_erc/foreign_bridge_test.js
=> Single execute signatures

contracts/libraries/Message.sol, contracts/upgradeable_contracts/BasicForeignBridge.sol, contracts/upgradeable_contracts/VersionableBridge.sol, contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol, contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, deploy/README.md, deploy/src/arbitrary_message/foreign.js, deploy/src/arbitrary_message/home.js, deploy/src/loadEnv.js, test/arbitrary_message/foreign_bridge.test.js, test/erc_to_erc/foreign_bridge.test.js, test/erc_to_native/foreign_bridge.test.js, test/helpers/helpers.js, test/native_to_erc/foreign_bridge_test.js
This merge contains the following set of improvements and fixes:
* [Improvement] Updated minimum gas usage estimation (#355), closes #352
* [Improvement] Simplified some conditions in require() clauses (#353)
* [Improvement] Single execute signatures (#357), closes #354
* [Fix] Fixes in AMB deployment related documentation and scripts (#358)
* [Other] badges links corrected to point to tokenbridge-contracts
It was decided to increase the major version of the release since the changes made under #357 are not backward compatible.
=> Merge the develop branch to the master branch, preparation to v4.0.0-rc0

contracts/libraries/Message.sol, contracts/upgradeable_contracts/BasicForeignBridge.sol, contracts/upgradeable_contracts/VersionableBridge.sol, contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol, contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, deploy/README.md, deploy/src/arbitrary_message/foreign.js, deploy/src/arbitrary_message/home.js, deploy/src/loadEnv.js, test/arbitrary_message/foreign_bridge.test.js, test/erc_to_erc/foreign_bridge.test.js, test/erc_to_native/foreign_bridge.test.js, test/helpers/helpers.js, test/native_to_erc/foreign_bridge_test.js
Reverts poanetwork/tokenbridge-contracts#359
I have accidentally pressed "Squash and Merge" so lost the links to the addressed issues.
=> Revert "Merge the develop branch to the master branch, preparation to v4.0.0-rc0"

package-lock.json, package.json
Update project version related to changes in #359
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/276
=> Bump version to 4.0.0-rc0

contracts/interfaces/IChai.sol, contracts/interfaces/IPot.sol, contracts/mocks/BridgeValidatorsDeterministic.sol, contracts/mocks/ChaiMock.sol, contracts/mocks/ChaiMock2.sol, contracts/mocks/DaiJoinMock.sol, contracts/mocks/DaiMock.sol, contracts/mocks/ForeignBridgeErcToNativeMock.sol, contracts/mocks/PotMock.sol, contracts/mocks/VatMock.sol, contracts/upgradeable_contracts/ChaiConnector.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, package-lock.json, test/erc_to_native/foreign_bridge.test.js, test/helpers/helpers.js
This merge contains the following set of improvements and fixes:
* [Improvement] Earning interest with Chai for erc-to-native mode (#356), closes #317
* [Fix] Added Bridge Validators deterministic mock for e2e tests (#366)
* [Fix] Add restriction on claiming Chai token (#368)
=> Merge the develop branch to the master branch, preparation to v4.0.0-rc1

package-lock.json, package.json
Update project version related to changes in #369
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/298
=> Bump version to 4.0.0-rc1

contracts/interfaces/IBlockReward.sol, contracts/mocks/BlockReward.sol, contracts/mocks/ForeignBridgeErcToNativeMock.sol, contracts/upgradeable_contracts/ChaiConnector.sol, contracts/upgradeable_contracts/erc20_to_erc20/FeeManagerErcToErcPOSDAO.sol, contracts/upgradeable_contracts/erc20_to_native/FeeManagerErcToNativePOSDAO.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, test/erc_to_native/foreign_bridge.test.js
This merge contains the following set of improvements and fixes:
* [Fix] Rename reward functions (#370)
* [Fix] Chai integration internal audit fixes (#372)
=> Merge the develop branch to the master branch, preparation to v4.0.0

package-lock.json, package.json
Update project version related to changes in #375 
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/301
=> Bump version to 4.0.0

package-lock.json, package.json
Update project version related to changes in #380
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/301
=> Bump version to 4.0.1

package-lock.json, package.json
Update project version related to changes in #386 
There is no impact on the oracle component. So, it is not required to update the submodule there.
=> Bump version to 4.0.2

contracts/ERC677BridgeToken.sol, contracts/ERC677BridgeTokenRewardable.sol, contracts/ERC677MultiBridgeToken.sol, test/erc677MultiBridgeToken.test.js, test/poa20_test.js
Closes https://github.com/poanetwork/tokenbridge-contracts/issues/388
=> Add support of multiple bridges in bridge token

contracts/mocks/PotMock.sol, contracts/upgradeable_contracts/ChaiConnector.sol, test/erc_to_native/foreign_bridge.test.js
=> Fix ChaiConnector behaviour when DSR is zero

package-lock.json, package.json
Update project version related to changes in #401
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/307
=> Bump version to 4.1.0

contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/ForeignAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/ForeignStakeTokenMediator.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/HomeAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/HomeStakeTokenMediator.sol, test/amb_erc677_to_erc677/foreign_bridge.test.js, test/amb_erc677_to_erc677/home_bridge.test.js, test/stake_token_mediators/foreign_mediator.test.js, test/stake_token_mediators/home_mediator.test.js
Emits `TokensBridged` event when `handleBridgedTokens` is called in mediators:
- `AMBErc677ToErc677`
- `StakeTokenMediator`
=> Add TokensBridged event in mediators

package-lock.json, package.json
Update project version related to changes in #413 
The changes have been verified under https://github.com/poanetwork/tokenbridge/pull/321
=> Bump version to 5.0.0-rc0

contracts/upgradeable_contracts/amb_erc677_to_erc677/callflows.md
In order to improve situation with absence of the development documentation I have prepared a detailed description of most important call flows for the STAKE AMB extension. It can also help for the security auditors in the future.
=> Detailed description of STAKE extension call flows

contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, package-lock.json, package.json
This version tag will contain the fix for the issue with possible endless loop based on an AMB message.
=> Bump version to 5.0.1 before merging to master

contracts/mocks/AMBMock.sol, contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol, contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, package-lock.json, package.json, test/amb_native_to_erc20/foreign_mediator.test.js, test/arbitrary_message/foreign_bridge.test.js, test/arbitrary_message/home_bridge.test.js
This updates provides a fix for a security issue addressed by
* [Fix] Fix infinite AMB message loop (#425)
In order to bump the version the following PR was also merged:
* [Other] Bump version to 5.0.1 before merging to master (#426)
=> Merge the develop branch to the master branch, preparation to v5.0.1

deploy/package-lock.json, deploy/package.json, deploy/src/amb_erc677_to_erc677/home.js, deploy/src/arbitrary_message/foreign.js, deploy/src/arbitrary_message/home.js, deploy/src/erc_to_erc/home.js, deploy/src/native_to_erc/foreign.js
=> Use eth_chainId instead of net_version

contracts/upgradeable_contracts/amb_native_to_erc20/HomeAMBNativeToErc20.sol, test/amb_native_to_erc20/home_mediator.test.js
=> Add missing call to setMediatorBalance

contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, test/arbitrary_message/foreign_bridge.test.js, test/arbitrary_message/home_bridge.test.js
=> Add AMB public chain id getters

contracts/upgradeable_contracts/BasicAMBMediator.sol, contracts/upgradeable_contracts/TokenBridgeMediator.sol
=> Remove nonce references in AMB mediators

package-lock.json, package.json
This version tag will contain few improvements to safe gas during deployment and to deploy a permit-able token for AMB extensions. It also contains a fix for the shift decimals feature.
=> Bump version to 5.2.0 before merging to master

package-lock.json, package.json
This version tag will contain a new pair of mediators. Also some legacy code was cleaned up.
=> Bump package version to 5.3.0

package-lock.json, package.json
This version tag will contain fixes for the the amb multi-erc20-to-erc20 mediator's pair.
=> Bump package version to 5.3.1

contracts/mocks/PermittableTokenMock.sol, contracts/upgradeable_contracts/BasicAMBMediator.sol, contracts/upgradeable_contracts/TokenBridgeMediator.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiTokenBridge.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeFeeManagerMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/MultiTokenBridgeMediator.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/callflows.md, deploy/README.md, deploy/src/loadEnv.js, deploy/src/multi_amb_erc20_to_erc677/initializeForeign.js, deploy/src/multi_amb_erc20_to_erc677/initializeHome.js, package-lock.json, package.json, test/multi_amb_erc20_to_erc677/foreign_mediator.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js, test/poa20_test.js
This update provides the following new functionalities and fixes:
* [Fix] increase the version of AMB contracts (#461)
* [Fix] Move fee manager into home mediator (#462)
* [Fix] Deinit token in fixFailedMessage (#463)
* [Other] Bump package version to 5.3.1 (#464)
=> Merge the develop branch to the master branch, preparation to v5.3.1

package-lock.json, package.json
This version contains migration to GitHub actions and improvements related to the omnibridge (former multi-token extension) contracts.
=> Bump package version to 5.4.0

.github/workflows/release.yml
=> Add automatic publishing of flattened sources

.github/workflows/release.yml, contracts/libraries/SafeERC20.sol, contracts/upgradeable_contracts/amb_erc20_to_native/BasicAMBErc20ToNative.sol, contracts/upgradeable_contracts/amb_erc20_to_native/ForeignAMBErc20ToNative.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/ForeignAMBErc677ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol, package-lock.json, package.json
This update provides the following new functionalities and fixes:
* [Fix] Extra check for balance increase (#479)
* [Other] Add automatic publishing of flattened sources (#478)
* [Other] Bump package version to 5.4.1 (#480)
=> Merge the develop branch to the master branch, preparation to v5.4.1

contracts/upgradeable_contracts/BaseMediatorFeeManager.sol
=> Correct handling of rewards addresses count

contracts/PermittableToken.sol, contracts/libraries/Message.sol
=> Add extra constraints on ECDSA signature parameters

contracts/upgradeable_contracts/BaseFeeManager.sol, contracts/upgradeable_contracts/FeeTypes.sol, contracts/upgradeable_contracts/RewardableBridge.sol
=> Add missing input fee type validation where needed

contracts/ERC677BridgeToken.sol, test/amb_erc20_to_native/foreign_mediator.test.js, test/multi_amb_erc20_to_erc677/foreign_mediator.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js, test/poa20_test.js
=> Update ERC677 behaviour

contracts/upgradeable_contracts/BaseMediatorFeeManager.sol, contracts/upgradeable_contracts/InterestReceiver.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, test/amb_native_to_erc20/foreign_mediator.test.js, test/amb_native_to_erc20/home_mediator.test.js, test/erc_to_native/foreign_bridge.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js
Closes #522 
Closes #523 
Closes #524
=> Add missing checks and return values

contracts/ERC677BridgeTokenRewardable.sol, contracts/PermittableToken.sol, contracts/libraries/Message.sol, contracts/libraries/TokenReader.sol, contracts/upgradeable_contracts/BaseMediatorFeeManager.sol, contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiTokenBridge.sol
=> Improve documentation in several methods

contracts/PermittableToken.sol, test/poa20_test.js
=> Reset expirations mapping after infinite approval

contracts/upgradeable_contracts/BaseOverdrawManagement.sol, contracts/upgradeable_contracts/BasicHomeBridge.sol, contracts/upgradeable_contracts/HomeOverdrawManagement.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol, contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol, contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol, contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol, test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js, test/amb_erc677_to_erc677/foreign_bridge.test.js, test/amb_erc677_to_erc677/home_bridge.test.js, test/erc_to_erc/home_bridge.test.js, test/erc_to_native/home_bridge.test.js
=> Fix overdraw management

contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, test/multi_amb_erc20_to_erc677/home_mediator.test.js
=> Disable fee collection if sender is a reward address

contracts/interfaces/IAMB.sol, contracts/mocks/Box.sol, contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, test/arbitrary_message/home_bridge.test.js
=> Support manual lane in AMB contracts

package-lock.json, package.json
This version introduce new feature for AMB and its mutli-token extension as well as provides few fixes.
=> Bump package version to 5.5.0

deploy/deploy.js, deploy/src/arbitrary_message/preDeploy.js
=> Add a pre-deploy script for AMB contracts

contracts/upgradeable_contracts/TokenBridgeMediator.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/MultiTokenBridgeMediator.sol, test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js, test/multi_amb_erc20_to_erc677/foreign_mediator.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js
=> Add TokensBridgingInitiated events to mediators

.github/workflows/main.yml, contracts/libraries/ArbitraryMessage.sol, contracts/mocks/AMBMock.sol, contracts/upgradeable_contracts/ReentrancyGuard.sol, contracts/upgradeable_contracts/TokenBridgeMediator.sol, contracts/upgradeable_contracts/amb_erc20_to_native/BasicAMBErc20ToNative.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol, contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicStakeTokenMediator.sol, contracts/upgradeable_contracts/amb_native_to_erc20/BasicAMBNativeToErc20.sol, contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/MultiTokenBridgeMediator.sol, deploy/deploy.js, deploy/src/arbitrary_message/preDeploy.js, package-lock.json, package.json, test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js, test/arbitrary_message/home_bridge.test.js, test/multi_amb_erc20_to_erc677/foreign_mediator.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js
This set of changes includes the following improvements and few fixes:
* [Improvement] Optimize use of temporary variables passed through storage (#555)
* [Improvement] Add TokensBridgingInitiated events to mediators (#556)
* [Improvement] Optimize Omnibridge gas usage (#553)
* [Fix] Add a pre-deploy chain id check for AMB contracts (#557), closes #554
* [Fix] Fix manuallane datatypes usage (#562)
* [Other] Attempt to fix a deprecated command
* [Other] Bump versions of changed contracts since last release (#564)
=> Merge the develop branch to the master branch, preparation to v5.6.0-rc0

contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, package-lock.json, package.json
The package and a AMB contract versions up-issue.
=> Bump package version to 5.6.0

contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeFeeManagerMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, package-lock.json, package.json, test/arbitrary_message/foreign_bridge.test.js, test/arbitrary_message/home_bridge.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js
This set of changes includes the following improvements and few fixes:
* [Improvement] Support custom minter contract for bridged stake token (#566)
* [Improvement] Allow minting of STAKE tokens on the Foreign side of the Omnibridge (#568)
* [Improvement] Allow to make new AMB requests while processing other messages (#572)
* [Fix] Add claimTokensFromTokenContract function for HomeMultiAMBErc20ToErc677 contract (#573)
* [Other] Bump package version to 5.6.0 (#575)
=> Merge the develop branch to the master branch, preparation to v5.6.0

contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol, test/arbitrary_message/foreign_bridge.test.js
=> Add safeExecuteSignatures* family of functions

contracts/helpers/AMBBridgeHelper.sol, contracts/helpers/Erc20ToNativeBridgeHelper.sol, contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiTokenBridge.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeFeeManagerMultiAMBErc20ToErc677.sol, contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol, package-lock.json, package.json, test/arbitrary_message/foreign_bridge.test.js, test/multi_amb_erc20_to_erc677/foreign_mediator.test.js, test/multi_amb_erc20_to_erc677/home_mediator.test.js, truffle-config.js
This set of changes includes the following improvements and few fixes:
* [Improvement] Helpers to collect signatures for erc20-to-native and AMB (#576)
* [Improvement] Deny reentrant execution of signatures in the ForeignAMB (#577)
* [Improvement] Add safeExecuteSignatures* family of functions (#587), closes #585, closes #586
* [Fix] Fix relayTokens for tokens supporting fees (#580)
* [Fix] Fix missing safeTransferFrom
* [Other] Disable per-token fees (#581)
* [Other] Disable per-token minPerTx (#582)
* [Other] Bump contracts and package version before 5.7.0-rc0 (#589)
=> Merge the develop branch to the master branch, preparation to v5.7.0-rc0

contracts/interfaces/IAMB.sol, contracts/interfaces/IAMBInformationReceiver.sol, contracts/mocks/Box.sol, contracts/upgradeable_contracts/arbitrary_message/AsyncInformationProcessor.sol, contracts/upgradeable_contracts/arbitrary_message/HomeAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, test/arbitrary_message/home_bridge.test.js
=> AMB Home-to-Foreign async calls

contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, package-lock.json, package.json
The package version updated due to changes made under #613 and #618
=> Bump package version before 6.0.0-rc1

contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol
As part of the AMB a gas limit for the call on the other side can be provided. The provided gas limit is
checked against a minimum gas usage computed based on the number of bytes within a call:
```solidity
function  getMinimumGasUsage(bytes _data) public pure returns (uint256 gas) {
// From Ethereum Yellow Paper
// 68 gas is paid for every non-zero byte of data or code for a transaction
// Starting from Istanbul hardfork, 16 gas is paid (EIP-2028)
return _data.length.mul(16);
}
```
However, as the call is made from within a smart contract, these costs do not apply. They only apply to initial calldata of a transaction. The dominating cost, namely the cost for the CALL itself (increased by EIP-2929) is not considered.
=> Use fixed lower call gas limit

contracts/gsn/BasePaymaster.sol, contracts/gsn/forwarder/IForwarder.sol, contracts/gsn/interfaces/GsnTypes.sol, contracts/gsn/interfaces/IPaymaster.sol, contracts/gsn/token_paymaster/TokenPaymaster.sol, contracts/libraries/Message.sol, contracts/mocks/XDaiForeignBridgeMock.sol, contracts/upgradeable_contracts/GSNForeignERC20Bridge.sol, contracts/upgradeable_contracts/InterestReceiverStakeBuyback.sol, contracts/upgradeable_contracts/InterestReceiverSwapToETH.sol, contracts/upgradeable_contracts/VersionableBridge.sol, contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol, contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol, contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol, contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol, contracts/upgradeable_contracts/erc20_to_native/CompoundConnector.sol, contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol, contracts/upgradeable_contracts/erc20_to_native/InterestConnector.sol, contracts/upgradeable_contracts/erc20_to_native/XDaiForeignBridge.sol, deploy/src/erc_to_native/foreign.js, deploy/src/loadContracts.js, package-lock.json, package.json, test/arbitrary_message/foreign_bridge.test.js, test/erc_to_native/foreign_bridge.test.js, test/erc_to_native/foreign_bridge_gsn.test.js
This update for the `master` branch contains the following set of changes made as part of closing of findings discovered during a security audit:
* [Fix] Stricter preconditions for payInterest (#623)
* [Fix] Fix offset in comments (#624)
* [Fix] Use fixed lower call gas limit (#627)
* [Fix] Separate XDaiForeignBridge contract with compound and GSN support (#626)
* [Fix] Update GSN interface (#628)
* [Fix] Block ERC20 selectors in AMB requests (#630)
* [Other] Bump package and contracts interfaces version prior to 6.0.0 (#629)
=> Merge the develop branch to the master branch, preparation to v6.0.0
