poanetwork/tokenbridge-contracts

- README.md
- contracts/upgradeable_contracts/U_ForeignBridge.sol
- contracts/upgradeable_contracts/U_HomeBridge.sol
- flats/ForeignBridge_flat.sol
- flats/HomeBridge_flat.sol
- migrations/3_upgradeable_deployment.js
- test/foreign_bridge_test.js
- test/home_bridge_test.js
Problem: Bridge should be able to limit amount of funds to be sent in 1 transaction
Solution: Provide maxPerTx method that also includes into `withinLimit` function
> Add max per tx

- contracts/upgradeable_contracts/U_ForeignBridge.sol
CollectedSignatures event extended to provide number of signatures used to confirm a particular withdraw transaction as so the bridge instance could use this number to fetch the corresponding number of signatures from the contract
**These changes will broke bridge functionality till the corresponding changes on the server's side are applied.**
> provide number of required signatures in CollectedSignatures event

- contracts/upgradeable_contracts/U_HomeBridge.sol
CollectedSignatures event extended to provide number of signatures used to confirm a particular deposit transaction as so the bridge instance could use this number to fetch the corresponding number of signatures from the contract
> provide number of required signatures in CollectedSignatures event (reversed bridge)

- contracts/ERC677BridgeToken.sol
- contracts/upgradeable_contracts/BridgeValidators.sol
1. The new version of openzeppelin Ownable contract has renounceOwnership function. See here. So this function is inherted by your ERC677BridgeToken silently. The function seems to be superfluous (not only for me). Is that necessary for your project?
Recomendations: Consider rewrite renounceOwnership to empty implementation (as you’ve done for finishMinting).
2.
BridgeValidators
1. Redundant checks/code
Severity: Minor
BridgeValidators.sol#L30. That check is redundant because of this and that.
Recomendations: Change require(...); to assert(...); or remove it.
Roman’s answer: Agree
Function does not generate event
Severity: Minor
initialize func set requiredSignatures var but does not generate RequiredSignaturesChanged(requiredSignatures); event. setRequiredSignatures does. Is it just not …
> Audit enhancements

- contracts/upgradeable_contracts/U_BridgeValidators.sol
See [this discussion](https://github.com/poanetwork/bridge-nodejs/issues/7) for why this is necessary.
Adding the index to the `ValidationRemoved` is not technically necessary now, but I added it for consistency.
> Index addresses of validator events

- contracts/upgradeable_contracts/U_BridgeValidators.sol
- test/validators_test.js
Adds `deployedAtBlock` function on BridgeValidators contract so we can know from which block start listening to events on the contract. See [this comment](https://github.com/poanetwork/bridge-nodejs/pull/47#discussion_r202377070)
> Add deployedAtBlock on BridgeValidators

- contracts/ERC677BridgeToken.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- package.json
- test/native_to_erc/home_bridge_test.js
- test/poa20_test.js
- test/testContracts/ERC677ReceiverTest.sol
- test/testContracts/RevertFallback.sol
this PR depends on #50 
Scenario:
1. Deploy a contract with `revert` in `fallback` on both chains: Home and Foreign
2. Use a bridge to initiate a transfer
3. Make sure the bridge still is able to send funds to recipient using self-destructed contract.
> Prevent an attack to send cross chain transfer using contract without payable fallback

- contracts/libraries/Message.sol
- contracts/upgradeable_contracts/BasicHomeBridge.sol
- test/erc_to_erc/home_bridge.test.js
- test/native_to_erc/home_bridge_test.js
This is necessary for https://github.com/poanetwork/bridge-nodejs/issues/56.
I also modified the library method to `internal` so that it's inlined in the bridge contract method. This is necessary because the deploy script is not deploying and linking the `Message` library, so using non-internal methods causes the deploy to fail.
> Add requiredMessageLength method to BasicHomeBridge contract

- deploy/deploy.js
When working on the bridge, I often do this:
```
cd submodules/poa-bridge-contracts/deploy
node deploy.js
cd -
```
when I could do:
```
node submodules/poa-bridge-contracts/deploy/deploy.js
```
Even better: we could have a npm script that deploys the contracts. Right now this isn't possible because the deploy script uses paths relative to the cwd of the process. This PR makes these paths independent.
> Allow using the deploy script from another directory

- contracts/ERC677BridgeToken.sol
- contracts/libraries/Version.sol
- contracts/upgradeable_contracts/BasicBridge.sol
- contracts/upgradeable_contracts/BridgeValidators.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/erc_to_erc/foreign_bridge.test.js
- test/erc_to_erc/home_bridge.test.js
- test/native_to_erc/foreign_bridge_test.js
- test/native_to_erc/home_bridge_test.js
- test/poa20_test.js
- test/validators_test.js
Closes #67 
Add `getBridgeMode` method on bridge contracts and add `getBridgeInterfacesVersion`  method on bridge, ERC677 token  and validators contract.
> Add bridge mode field and interfaces version support

- deploy/src/erc_to_erc/foreign.js
To address #86.
Since this version of contracts code was audited and tested it is not desirable to change them on this stage of the development. But the issue is critical for the deployment of the bridge in `erc-to-erc` mode.
That's why a quick fix to address the issue was introduced on the deployment script side. This allows to avoid changes in the contracts code.
The proper fix will be done in #91.
> Gas Price initialization for Foreign Bridge in erc-to-erc mode

- contracts/upgradeable_contracts/RewardableBridge.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- deploy/.env.example
- deploy/README.md
- deploy/src/deploymentUtils.js
- deploy/src/erc_to_native/home.js
- deploy/src/loadEnv.js
- test/erc_to_native/home_bridge.test.js
Closes #124 
In order to be able to initialize the bridge with Fee Manager address and Fee value, I had to add a new initialize method that accepted that 2 extra parameters because `setFeeManagerContract` and `setFee` methods can only be executed by the owner which can be different from `DEPLOYMENT_ACCOUNT`.
> Update deploy script to include Fee Manager options for ERC-TO-NATIVE mode

- contracts/upgradeable_contracts/native_to_erc20/FeeManagerNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- deploy/README.md
- deploy/src/loadEnv.js
- deploy/src/native_to_erc/foreign.js
- deploy/src/native_to_erc/home.js
- test/native_to_erc/foreign_bridge_test.js
- test/native_to_erc/home_bridge_test.js
After we agree on the changes, we need to update gas consumption documentation. 
Here are some details on the test I performed on `Sokol-Kovan`
```
[   Home  ] HomeBridge: 0x49aFC1efE3A8F96dc9630C57E899c26962832987 at block 6786841
[ Foreign ] ForeignBridge: 0x31115c831fe0393A2251E89D2BEDccF91a03411f at block 10162289
[ Foreign ] ERC677 Bridgeable Token: 0xF95c48e20267a74920E5bA84ef7C653e27E80289
VALIDATORS
==========
1: 0x3752F0a521b2E383693f658D6FC377953024C207, reward address 0xFE365A92Bc01425441dE76D8EDA48496B64446FB
2: 0xcfeF0C6Bb765321529FfE81507f6d099693CD225, reward address 0xcfeF0C6Bb765321529FfE81507f6d099693CD225
3: 0xf4BEF13F9f4f2B203FAF0C3cBbaAbe1afE056955, reward address 0xf4BEF13F9f4f2B203FAF0C3cBbaAbe1afE056955
Required signatures: 1
Validator running token-bridge: …
```
> Add Fee Manager implementation for Native-to-ERC mode

- deploy/README.md
Replace ~poa.infura.io~ with core.poa.network in README
Infura RPC endpoint for POA Core [has been disabled](https://forum.poa.network/t/infuras-poa-core-nodes-to-be-disabled-on-2-1-19/1881)
> Replace poa.infura.io with core.poa.network

- contracts/upgradeable_contracts/BaseFeeManager.sol
- contracts/upgradeable_contracts/FeeTypes.sol
- contracts/upgradeable_contracts/RewardableBridge.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/RewardableHomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/RewardableForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/RewardableHomeBridgeNativeToErc.sol
- deploy/.env.example
- deploy/README.md
- deploy/src/erc_to_native/home.js
- deploy/src/loadEnv.js
- deploy/src/native_to_erc/foreign.js
- deploy/src/native_to_erc/home.js
- docs/ERC-TO-NATIVE-WITH-REWARD.md
- docs/ERC-TO-NATIVE.md
- docs/NATIVE-TO-ERC-WITH-REWARD.md
- docs/NATIVE-TO-ERC.md
- test/erc_to_native/home_bridge.test.js
- test/native_to_erc/foreign_bridge_test.js
- test/native_to_erc/home_bridge_test.js
Added the following methods:
- setHomeFee
- getHomeFee
- setForeignFee
- getForeignFee
I had to update `calculateFee` to receive a parameter to know which fee it should use.
> If the Fee Manager is in manages-one-direction mode (see #148) the method setFee will proxy one of the methods setHomeFee and setForeignFee depending on the side where the contract is deployed. Similar is for getFee.
Regarding this comment, I removed `setFee` and `getFee` since I couldn't find a use case for them unless I'm missing something. On bridge-ui using `getFeeManagerMode` I think it will be enough to know which fee to use.
Closes #149
> Separate fee into home fee and foreign fee

- contracts/ERC677BridgeTokenRewardable.sol
- test/poa20_test.js
These changes are to disallow sending tokens directly to [`ValidatorSet`](https://github.com/poanetwork/posdao-contracts/blob/master/contracts/ValidatorSetAuRa.sol) contract because the tokens must only be sent to `ValidatorSet` by [`stake`](https://github.com/poanetwork/posdao-contracts/blob/e47975b152c766625d2a9d49995d3028fe922487/contracts/abstracts/ValidatorSetBase.sol#L149-L156) function.
> Override `transfer` and `transferFrom` in `ERC677BridgeTokenRewardable`

- contracts/ERC677BridgeTokenRewardable.sol
- contracts/test/Staking.sol
- contracts/test/ValidatorSet.sol
- deploy/.env.example
- deploy/README.md
- deploy/src/erc_to_erc/home.js
- deploy/src/loadEnv.js
- deploy/src/native_to_erc/foreign.js
- test/mockContracts/ERC677BridgeTokenRewardableMock.sol
- test/poa20_test.js
We have [split ValidatorSet](https://github.com/poanetwork/posdao-contracts/commit/4303896907b29df65774ea1a2adefa9c0a097123) contract in [`posdao-contracts`](https://github.com/poanetwork/posdao-contracts) repo into two separate contracts: [`ValidatorSet`](https://github.com/poanetwork/posdao-contracts/blob/4303896907b29df65774ea1a2adefa9c0a097123/contracts/ValidatorSetAuRa.sol) and [`Staking`](https://github.com/poanetwork/posdao-contracts/blob/4303896907b29df65774ea1a2adefa9c0a097123/contracts/StakingAuRa.sol).
Now, the ERC677 bridge token should work with the `Staking` contract instead of `ValidatorSet`.
Also, `DEPLOY_REWARDABLE_TOKEN` config option was added for `erc-to-erc` bridge mode.
> Rename ValidatorSet contract to Staking contract

- deploy/README.md
- Changed configuration options for `FOREIGN_DAILY_LIMIT` and `FOREIGN_MAX_AMOUNT_PER_TX`, and commented out  `FOREIGN_MIN_AMOUNT_PER_TX`,  for `erc20-to-erc20` and `erc20-to-native` bridge modes.
- Modified several comments for line length
> update FOREIGN_DAILY_LIMIT & FOREIGN_MAX_AMOUNT_PER_TX for bridge modes

- .travis.yml
- contracts/upgradeable_contracts/BasicForeignBridge.sol
- contracts/upgradeable_contracts/RewardableBridge.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/native_to_erc/foreign_bridge_test.js
Fee distribution events were introduced in https://github.com/poanetwork/poa-bridge-contracts/pull/171. It seems logical define events in a contract which is extended by bridge contracts that work with a fee manager rather than define them in every bridge contract.
> Fee distribution events in the RewardableBridge contract

- flatten.sh
The contracts `ClassicEternalStorageProxy` and `ClassicHomeBridgeNativeToErc` were missed to be flattened in #181.
> Flattening of contracts related to the bridge on Ethereum Classic 

- deploy/src/erc_to_erc/foreign.js
- deploy/src/erc_to_erc/home.js
- deploy/src/erc_to_native/foreign.js
Fixed a bug that was found while running oracle e2e tests on https://github.com/poanetwork/tokenbridge/pull/67. This bug was introduced on PR https://github.com/poanetwork/poa-bridge-contracts/pull/156. It causes to call `initialize` method of bridge validators on the implementation contract instead of the proxy contract on deployment script.
This issue affected:
- Home side of ERC_TO_ERC
- Foreign side of ERC_TO_ERC
- Foreign side of ERC_TO_NATIVE
> Fix bad initialization of bridge Validators on deploy script

- .travis.yml
Right now on every PR travis display `The Travis CI build passed` when the unit tests build passed ignoring if the coverage build passed or not and do not display any information related to that job.
This PR removes that coverage build is allow to fail, and now travis will wait until both jobs are completed to display if the builds are passing or not
> Remove coverage build from allow_failures on travis

- REWARD_MANAGEMENT.md
closes #196 
- Updated pictures in `erc20-to-erc20` mode
- Added `erc20-to-native` case  when fees are distributed among the network validators
> Update reward management docs

- contracts/upgradeable_contracts/BaseBridgeValidators.sol
- contracts/upgradeable_contracts/BasicBridge.sol
- contracts/upgradeable_contracts/BasicHomeBridge.sol
- contracts/upgradeable_contracts/BridgeValidators.sol
- contracts/upgradeable_contracts/OverdrawManagement.sol
- contracts/upgradeable_contracts/RewardableValidators.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/POSDAOHomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/erc_to_erc/foreign_bridge.test.js
- test/erc_to_native/foreign_bridge.test.js
Changes included in this PR:
- Remove duplicate modifier on claimTokens method https://github.com/poanetwork/poa-bridge-contracts/commit/260cd5613bd49091f36de9f8f31a725f680b603b
- Fix multiple reads of totalBurntCoins https://github.com/poanetwork/poa-bridge-contracts/commit/51e7d9f7638de98c8c01c3ab2603a9957381764d
- Remove parameter on setInitialize https://github.com/poanetwork/poa-bridge-contracts/commit/8fc613bdcb9cf589ad7a64870d7b5bbefeaf8dc2
- Remove status parameter on setFixedAssets https://github.com/poanetwork/poa-bridge-contracts/commit/88d4d5ab70af08f303e839d5cb707aa8fc9d888d
- Remove unused fireEventOnTokenTransfer on HomeBridgeErcToNative https://github.com/poanetwork/poa-bridge-contracts/commit/db9436cc8d5e31a996652009f52054595129a65c
- Redefine empty block methods on …
> several minor fixes

- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
Closes #215 
Reviewed all method that returns values, fixed internal methods `_initialize` and `_rewardableInitialize` which shouldn't return any value
> Remove returns from internal initialize method on HomeBridgeErcToErc

- contracts/upgradeable_contracts/BasicForeignBridge.sol
- contracts/upgradeable_contracts/BasicHomeBridge.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
Closes #212 
All the Home contracts had the same implementation for `affirmationWithinLimits` which calls `withinExecutionLimit` that is defined on `BasicBridge`. It made sense to me to call direclty the method `withinExecutionLimit` from `BasicHomeBridge` and remove `affirmationWithinLimits`. 
In order to do that, I had to change the inheritance of `BasicBridge`. Now `BasicHomeBridge` extends from `BasicBridge` and Home contracts do it througth `BasicHomeBridge`. The changes mentioned are included in this commit https://github.com/poanetwork/poa-bridge-contracts/commit/e314ee373196812c738465eed0754decfada5c2c
I found that this same situation was repeated for `messageWithinLimits` on `BasicForeignBridge` so I applied similar changes to that method too. These are the changes …
> Remove duplicated logic on top of withinExecutionLimit

- contracts/ERC677BridgeToken.sol
- contracts/ERC677BridgeTokenRewardable.sol
- contracts/upgradeable_contracts/ERC677Bridge.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/FeeManagerErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
Closes #217 
Besides of duplicate checks on `ERC677BridgeTokenRewardable`, this pattern was also repeated on other contracts so I applied the changes to these contracts too.
> Remove duplicated checks of contracts

- contracts/interfaces/IUpgradeabilityOwnerStorage.sol
- contracts/upgradeable_contracts/BasicBridge.sol
- contracts/upgradeable_contracts/OverdrawManagement.sol
- contracts/upgradeable_contracts/Upgradeable.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErcPOSDAO.sol
- deploy/src/erc_to_erc/home.js
- deploy/src/loadContracts.js
- flatten.sh
- test/erc_to_erc/home_bridge.test.js
Closes #208 
- Renamed `POSDAOHomeBridgeErcToErc` to `HomeBridgeErcToErcPOSDAO`
- Renamed interface `IOwnedUpgradeabilityProxy` to `IUpgradeabilityOwnerStorage` to match the name of the contract where method `upgradeabilityOwner()` is defined.
- Renamed `OwnedUpgradeability` to `Upgradeable`. I think this one was the more confusing, all the contracts that includes the name `upgradeability` adds functionality to the proxy contract but this one was more about consuming methods exposed by those contracts from the implementation contract. 
Please let me know if you can think of a better name for the updated contracts
> Improve contracts names

- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- test/native_to_erc/foreign_bridge_test.js
I found that all home and foreign contracts had checks for `_requiredBlockConfirmations` parameter on `initialize` method except for `ForeignBridgeNativeToErc`. This PR adds the missing check.
>  Fix missing required block confirmation check in ForeignBridgeNativeToErc

- contracts/ERC677BridgeToken.sol
- contracts/ERC677BridgeTokenRewardable.sol
- contracts/interfaces/IBlockReward.sol
- contracts/interfaces/IBridgeValidators.sol
- contracts/interfaces/IRewardableValidators.sol
- contracts/interfaces/IUpgradeabilityOwnerStorage.sol
- contracts/upgradeability/OwnedUpgradeabilityProxy.sol
- contracts/upgradeability/UpgradeabilityStorage.sol
- contracts/upgradeable_contracts/BaseBridgeValidators.sol
- contracts/upgradeable_contracts/BaseFeeManager.sol
- contracts/upgradeable_contracts/BasicBridge.sol
- contracts/upgradeable_contracts/BasicHomeBridge.sol
- contracts/upgradeable_contracts/BridgeValidators.sol
- contracts/upgradeable_contracts/Ownable.sol
- contracts/upgradeable_contracts/RewardableBridge.sol
- contracts/upgradeable_contracts/RewardableValidators.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/FeeManagerErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErc677ToErc677.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_native/FeeManagerErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/FeeManagerErcToNativePOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/FeeManagerNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/FeeManagerNativeToErcBothDirections.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
Closes #233 
All methods from the list were updated except the following:
- **BasicBridge.sol	120** `function withinLimit(uint256 _amount)`
- **BasicBridge.sol	125** `function withinExecutionLimit(uint256 _amount)`
Because both methods are called internally from other methods.
- **ForeignBridgeErcToNative.sol 47**
- **BasicForeignBridgeErcToErc.sol	42**
Because `claimTokens` method is overriding `claimTokens` from BasicBridge and also calling it by `super.claimTokens`, so both methods should have the same visibility and using `external` does not work with `super` which triggers an internal call.
- **ForeignBridgeErc677ToErc677.sol	43**
- **ForeignBridgeErcToErc.sol	31**
Because `erc20token()` is being used by internals calls too.
- **IBurnableMintableERC677Token.sol	6**	 
- …
> Use external modifier instead of public

- contracts/ERC677BridgeTokenRewardable.sol
`_receivers.length` was taken out the `for` loop to optimize the `mintReward` function a bit because that value was copied from `calldata` to `memory` on every loop iteration.
> Slightly optimize the `ERC677BridgeTokenRewardable.mintReward` function

- contracts/test/FeeManagerMock.sol
- contracts/upgradeable_contracts/BaseFeeManager.sol
- package.json
- test/erc_to_native/home_bridge.test.js
Closes #245 
- Updated `random` method visibility
- Added `FeeManagerMock` to explicitly test that method
- Fixed `lint:sol:prettier:fix` npm script
> Fix random method visibility in BaseFeeManager

- README.md
Currently on `master` it's broken. The reason is changing the package name by https://github.com/poanetwork/poa-bridge-contracts/pull/230
> Update readme with new travis link

- contracts/ERC677BridgeTokenRewardable.sol
- test/poa20_test.js
These changes remove redundant `require` (since SafeMath is already used there) and `withdraw` function from the `ERC677BridgeTokenRewardable` (since it is the same as `transfer` ERC20 function).
> Remove redundant code from ERC677BridgeTokenRewardable contract

- contracts/upgradeability/EternalStorageProxy.sol
The layout of the state variables between the `EternalStorageProxy` and implementation contracts were inconsistent. Reading a value of `EternalStorage` from the proxy could lead to read an incorrect value. 
This PR fixes the inheritance and now `EternalStorageProxy` has the same order of the inherited contracts as `ClassicEternalStorageProxy`
> Fix EternalStorageProxy inheritance

- contracts/upgradeable_contracts/BasicBridge.sol
- test/erc_to_native/home_bridge.test.js
- test/native_to_erc/home_bridge_test.js
Add parameter check in `setDailyLimit` and `setExecutionDailyLimit` methods to maintain consistency of `minPerTx < MaxPerTx < dailyLimit` and `executionMaxPerTx < executionDailyLimit`.
`dailyLimit` and `executionDailyLimit` can still be set to `0` if needed to stop bridge operations.
> Add parameter check in setDailyLimit and setExecutionDailyLimit methods

- contracts/ERC677BridgeToken.sol
- contracts/ERC677BridgeTokenRewardable.sol
- contracts/upgradeability/UpgradeabilityProxy.sol
- contracts/upgradeable_contracts/BasicBridge.sol
- contracts/upgradeable_contracts/ERC677Bridge.sol
- contracts/upgradeable_contracts/RewardableBridge.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/FeeManagerErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/native_to_erc/home_bridge_test.js
The default behavior of `delegatecall` returns `true` if the contract does not exist. Because of that, it makes sense to check `extcodesize > 0` when setting the implementation contract.
We have repeated implementations of the method `isContract` in different contracts. I removed all the implementation and used the `openzeppelin-solidity` implementation of this method which is exactly the same.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0e65947efbffc592cffea8c2ae9d3b8e11659854/contracts/AddressUtils.sol#L16-L27
> Check proxy upgrade contract code

- contracts/upgradeable_contracts/BridgeValidators.sol
- contracts/upgradeable_contracts/RewardableValidators.sol
Moved `setValidatorCount` call out of the `for` loop to save gas
> Improve initialize method's gas usage in validator contracts

- contracts/upgradeable_contracts/ERC677Bridge.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
Since `ERC677Bridge` implements `ERC677Receiver` interface, it makes sense that `ERC677Bridge` inherit directly from that contract
> Update ERC677Bridge to inherit from ERC677Receiver

- contracts/interfaces/IBurnableMintableERC677Token.sol
- contracts/upgradeability/UpgradeabilityStorage.sol
- contracts/upgradeable_contracts/BasicForeignBridge.sol
This PR includes 3 minor fixes:
-  Removed unused `SafeMath` in `BasicForeignBridge`
-  Add name to mint parameters for consistency in `IBurnableMintableERC677Token`
- Fix return comment in `version` method of `UpgradeabilityStorage` contract
> Minor fixes on contracts

- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErc677ToErc677.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/erc_to_erc/foreign_bridge.test.js
- test/erc_to_erc/home_bridge.test.js
- test/erc_to_native/foreign_bridge.test.js
- test/erc_to_native/home_bridge.test.js
- test/native_to_erc/foreign_bridge_test.js
- test/native_to_erc/home_bridge_test.js
See [this comment](https://github.com/poanetwork/poa-bridge-contracts/pull/258#pullrequestreview-270567806), this will allow all the values to be included in the event history correctly.
> Add missing events in initialize methods

- .travis.yml
- codechecks.yml
- package-lock.json
- package.json
This PR add the [eth-gas-reporter codecheck](https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md) CI integration that displays a pull request's gas consumption changes relative to its target branch in the Github UI.
> Add eth-gas-reporter codecheck for gas usage report on CI

- contracts/ERC677BridgeTokenRewardable.sol
- test/poa20_test.js
This little change ensures that [`StakingAuRa`](https://github.com/poanetwork/posdao-contracts/blob/master/contracts/StakingAuRa.sol) contract has no tokens on its balance before its address is set to the `ERC677BridgeTokenRewardable.stakingContract` variable. The `StakingAuRa` contract must have zero balance when the network starts. The same checking was added to the `StakingAuRa.setErc20TokenContract` function: https://github.com/poanetwork/posdao-contracts/commit/2f3449b765494af346503a3de52f0fdfbe425eef#diff-d272eb6253b6a8415de90563f08ebb92
> Enhance setStakingContract function

- contracts/interfaces/IAMB.sol
- contracts/mocks/IAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/ForeignAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/HomeAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol
- test/arbitrary_message/foreign_bridge.test.js
- test/arbitrary_message/home_bridge.test.js
Closes #281 
Implemented the approach mentioned in [this comment](https://github.com/poanetwork/poa-bridge-contracts/issues/281#issuecomment-529516782).
Also added `indexed` property to parameters of AMB events. This could be useful for filtering events from/to a specific mediator or by transaction hash.
> Add result information for AMB message call

- contracts/ERC677BridgeTokenRewardable.sol
- contracts/mocks/BlockReward.sol
- test/erc_to_erc/home_bridge.test.js
- test/poa20_test.js
These changes simplify the `ERC677BridgeTokenRewardable.mintReward` function as now it should accept one and only receiver instead of an array of receivers, and restrict direct sending tokens to BlockReward contract.
Now, the `mintReward` should only mint the reward amount of tokens for the BlockReward contract address.
We changed the logic of reward distribution in the `posdao-contracts` so that the participants will manually claim the reward from the BlockReward contract instead of receiving the rewards automatically.
The corresponding changes in the `posdao-contracts` repo:
- https://github.com/poanetwork/posdao-contracts/commit/53aeb0d3405360d82a26ec768581dcbfef5faed8#diff-a28c1847216ad8b585ba61d0dde47598
- https://github.com/poanetwork/posdao-contracts/commit/d2f388723eeedf88693646ca3 …
> Simplify the `ERC677BridgeTokenRewardable.mintReward` function

- contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol
- test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js
This PR fixes a bug that causes `setTotalSpentPerDay` to be called twice when an erc677 invokes `relayTokens` in `AMB-ERC-TO-ERC` mode.
With this fix `totalSpentPerDay` is correctly updated for the following scenarios:
- ERC20 calling `relayTokens`
- ERC677 calling `relayTokens`
- ERC677 calling `transferAndCall` direclty
> Fix setTotalSpentPerDay called twice in AMB-ERC-TO-ERC

- contracts/interfaces/IScdMcdMigration.sol
- contracts/mocks/DaiAdapterMock.sol
- contracts/mocks/ScdMcdMigrationMock.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- test/erc_to_native/foreign_bridge.test.js
Closes #310 
Tested the implementation with MakerDAO contracts in Kovan testnet:
- Sai Address: `0xc4375b7de8af5a38a93548eb8453a498222c4ff2`
- Dai Address: `0x1d7e3a1a65a367db1d1d3f51a54ac01a2c4c92ff`
- ScdMcdMigration Address: `0x97cb5a9abcdbe291d0cd85915fa5b08746fe948a`
- [Full list of MakerDAO contracts on Kovan](https://changelog.makerdao.com/releases/kovan/0.2.15/contracts.json) 
Foreign Bridge Address: [`0x61429A7ac9e32531f52C181C15ca453e6f5E9e8B`](https://blockscout.com/eth/kovan/address/0x61429a7ac9e32531f52c181c15ca453e6f5e9e8b)
`migrateToMCD` call: [`0x1a96964024175ce0a93f4da41603f9a8ea173d0e88c84336eee23809013eb8e6`](https://blockscout.com/eth/kovan/tx/0x1a96964024175ce0a93f4da41603f9a8ea173d0e88c84336eee23809013eb8e6)
> Add method to migrate from SCD to MCD

- deploy/README.md
- deploy/deploy.js
- deploy/src/amb_erc677_to_erc677/foreign.js
- deploy/src/amb_erc677_to_erc677/home.js
- deploy/src/amb_erc677_to_erc677/initialize.js
The changes are to reflect AMB specific.
Now the output of the deployment script looks like following:
```
Bridge contract deployment started
Bridge mode: AMB_ERC_TO_ERC
[Home] Deploying Bridge Mediator storage
pending txHash 0x727b905d3c6f12df4fadc7f1add2a93ec3ba53a7259875f739953c202799b584
[Home] Bridge Mediator Storage:  0x8D2Aa2C0527a9DD42B6b142dFe678f329Fa7dfbE
[Home] Deploying Bridge Mediator implementation
pending txHash 0x2e556c09c4ea31ea90bed9374c53d6334d18f27d5866c005d8743b91cd9d7df7
[Home] Bridge Mediator Implementation:  0x1c1Ab9debf161fB006BD313A69BD41F7EF1706A9
[Home] Hooking up Mediator storage to Mediator implementation
pending txHash 0x6f372c902ef44da37d88ed929f50fb45ee4058f4aeb530e935693821c546db79
[Home] deploying Bridgeable token
pending txHash …
```
> Wording changes in the erc677-to-erc677 bridge on top of AMB deployment scripts

- contracts/upgradeable_contracts/BasicTokenBridge.sol
- test/erc_to_native/home_bridge.test.js
Closes #322 
`setMaxPerTx` now allows to set `0` limit in order to temporarily stop the bridge. Otherwise, if not `0`, new max limit should be greater than `minPerTx()`.
`setMinPerTx` additionally checks that new limit is positive.
> Updated checks in setMinPerTx and setMaxPerTx

- contracts/libraries/Message.sol
- scripts/test.sh
- test/arbitrary_message/foreign_bridge.test.js
- test/erc_to_erc/foreign_bridge.test.js
- test/erc_to_native/foreign_bridge.test.js
- test/helpers/helpers.js
- test/native_to_erc/foreign_bridge_test.js
Closes #327 
- Fixed bug, related to `uint8` truncation in `Message.sol` library.
- Added tests for covering maximum possible required signatures.
> Max signatures limit

- contracts/upgradeability/ClassicEternalStorageProxy.sol
- contracts/upgradeability/EternalStorageProxy.sol
- contracts/upgradeable_contracts/BridgeValidators.sol
- contracts/upgradeable_contracts/Ownable.sol
- contracts/upgradeable_contracts/RewardableValidators.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErc677ToErc677.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/rewardable_validators_test.js
- test/validators_test.js
Closes #323 
Contracts for `EternalStorageProxy` and `ClassicEternalStorageProxy` initialise owner in storage to `msg.sender`.
Added modifier then works as follows:
- If contract is called directly, without proxy, so that owner is not set initially, it allows to call `initialize()` without any restrictions.
- When proxy is used, owner in `EternalStorage` is set initially to contract deployer, so only current owner is allowed to call `initialize()`.
- When proxy implementation is updated through `updateAndCall()`, ownership is checked in `onlyUpgradeabilityOwner` modifier, so that only proxy owner will be able to perform upgrade.
> Added Initialize functions access control modifier

- README.md
After the repo name update the badges links became broken.
This PR can be considered as part of the work for #312.
> Update for badges links to work with new contracts repo name

- contracts/libraries/Message.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol
It seems to me, that some of the `requires` for AMB bridge can be simplified, doing so may save some gas during execution.
> Simplified require conditions for AMB bridge

- deploy/README.md
- deploy/src/arbitrary_message/foreign.js
- deploy/src/arbitrary_message/home.js
- deploy/src/loadEnv.js
As part of the AMB deployment to the real chains it was found that deployment scripts produce inaccurate and ambiguous output. 
Also it was found that the example of configuration `.env` file contains obsoleted parameters.
Finally, the module checking correctness of configuration parameters was changed to not require setup of `DEPLOY_REWARDABLE_TOKEN` parameter.
> Fixes in AMB deployment related documentation and scripts 

- contracts/mocks/BridgeValidatorsDeterministic.sol
Added `BridgeValidators` mock for `oracle-e2e` tests fix. See https://github.com/poanetwork/tokenbridge/pull/294
> Added BridgeValidators mock

- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- test/erc_to_native/foreign_bridge.test.js
It was found that the pervious version of contracts allowed to claim chai tokens. This is considered to be insecure.
Fixed that by adding one more validation in `claimTokens` function of `ForeignBridgeErcToNative`.
> Restriction on claiming Chai token

- contracts/interfaces/IBlockReward.sol
- contracts/mocks/BlockReward.sol
- contracts/upgradeable_contracts/erc20_to_erc20/FeeManagerErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_native/FeeManagerErcToNativePOSDAO.sol
Renames `BlockReward.addBridgeTokenFeeReceivers` to `addBridgeTokenRewardReceivers` and `addBridgeNativeFeeReceivers` to `addBridgeNativeRewardReceivers` according to the latest changes in POSDAO contracts: https://github.com/poanetwork/posdao-contracts/commit/97858990b7c985983d61d4e0c39fd6ac62a55e23
I decided to rename `Fee` to `Reward` because there can be a reward from the bridge which is not only fee - for example, the scheme https://www.staketoken.net/token-model/reward-mechanics/xdai-rewards assumes that the Interest may be distributed to stakers in xDai coins from the bridge (that could be done through the `BlockReward.addBridgeNativeRewardReceivers` function previously named `addBridgeNativeFeeReceivers`)
> Rename BlockReward functions

- contracts/ERC677BridgeToken.sol
- deploy/src/deploymentUtils.js
- deploy/src/erc_to_erc/preDeploy.js
- docs/ERC-TO-ERC.md
- docs/NATIVE-TO-ERC-WITH-REWARD.md
- docs/NATIVE-TO-ERC.md
- test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js
- test/poa20_test.js
Renames `ERC677BridgeToken.setBridgeContract` to `setBridgeContracts` and `ERC677BridgeToken.bridgeContract()` to `bridgeContracts()`.
Since the `ERC677BridgeToken` is not upgradable, we need to have an ability to set multiple addresses as there can be different bridges (in the future).
> Allow multiple bridges for token

- contracts/ERC677BridgeToken.sol
- deploy/src/deploymentUtils.js
- deploy/src/erc_to_erc/preDeploy.js
- docs/ERC-TO-ERC.md
- docs/NATIVE-TO-ERC-WITH-REWARD.md
- docs/NATIVE-TO-ERC.md
- test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js
- test/poa20_test.js
Reverts poanetwork/tokenbridge-contracts#387.
After discussion with @varasev it was decided to revert the changes to introduce another approach: a separate contract with the support of multiple bridges that will be used only with AMB mediators. This approach could get rid of the changes on the oracle/monitor side.
> Revert "Allow multiple bridges for token"

- contracts/interfaces/IGasToken.sol
- contracts/mocks/ForeignAMBWithGasTokenMock.sol
- contracts/mocks/GasTokenMock.sol
- contracts/upgradeable_contracts/GasTokenConnector.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/ForeignAMBWithGasToken.sol
- flatten.sh
- test/arbitrary_message/foreign_bridge.test.js
This PR adds functionality of minting gas tokens inside `requireToPassMessage` call of foreign AMB bridge
> Gas token integration

- package-lock.json
- package.json
- upgrade/src/upgradeBridgeOnHome.js
New implementation of the bridge contract for the xDai chain: https://blockscout.com/poa/xdai/address/0x26077961Db25E38032eD3C30e5791444fa686D68/contracts
As soon as the proxy contract is updated with the reference to the new implementation, the `prepareToPOSDAO()` is called.
The previous implementation of the bridge contract: https://blockscout.com/poa/xdai/address/0xC7b4618d03a756f8345Bd1bF1cCCbe3681f823Ef/contracts
> Call prepareToPOSDAO as part of upgrade home bridge implementation

- contracts/mocks/InterestReceiverMock.sol
- contracts/upgradeable_contracts/InterestReceiver.sol
- deploy/src/utils/deployInterestReceiver.js
- test/erc_to_native/foreign_bridge.test.js
This PR optimizes `InterestReceiver` for usage without `EternalStorage`, since it will be deployed without proxy contract. 
Continues #380
> Update interest receiver

- contracts/ERC677BridgeToken.sol
Below is the list of the reason why these changes were introduced:
1. It was found that `abi.encodeWithSelector` is worth to use instead of `abi.encodeWithSignature` since the contract storage is used in more efficient way.
2. Other places where `onTokenTransfer` is being called uses `abi.encodeWithSelector`.
* [ChaiConnector.sol](https://github.com/poanetwork/tokenbridge-contracts/blob/3bc2b08feffb45a3e780f1703c51f971850f9c1d/contracts/upgradeable_contracts/ChaiConnector.sol#L186)
* [GasTokenConnector.sol](https://github.com/poanetwork/tokenbridge-contracts/blob/3bc2b08feffb45a3e780f1703c51f971850f9c1d/contracts/upgradeable_contracts/GasTokenConnector.sol#L91)
> Consistent call of onTokenTransfer 

- contracts/upgradeable_contracts/VersionableBridge.sol
During a code inspection it was found that the bridge interfaces version is inconsistent with the release version. But [the bridge API was changed](https://github.com/poanetwork/tokenbridge-contracts/pull/357) as so it is not compatible any more with the contracts of version 3.0.0
> Synchronization of interfaces version with the release versioning

- test/erc_to_native/foreign_bridge.test.js
As it was found in https://github.com/poanetwork/tokenbridge-contracts/pull/410#issuecomment-623323516, https://travis-ci.org/github/poanetwork/tokenbridge-contracts/jobs/682811252 , tests for disabled DSR can behave differently.
This happens because of the great amount of delays in these tests and the fact that runs with enabled coverage are much slower.
This PR removes all asserts which rely on a particular timing.
> Remove redundant asserts in Zero DSR tests

- .dockerignore
- .gitignore
- Dockerfile
- contracts/upgradeable_contracts/amb_erc677_to_erc677/HomeStakeTokenFeeManager.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/HomeStakeTokenMediator.sol
- test/stake_token_mediators/home_mediator.test.js
Logically the mediator should not be aware about the process how fees are distributed, this should lay on the fee manager shoulders. That's why the code to send fee to the block reward contract was moved to the fee manager.
> Hiding of fee distribution implementation

- contracts/mocks/BlockReward.sol
Update method `addBridgeTokenRewardReceivers` from our block reward mock to match the implementation and emit the same event from 
https://github.com/poanetwork/posdao-contracts/blob/c14fddb6bc9863f5d2c2075df3d755eb7637c712/contracts/base/BlockRewardAuRaTokens.sol#L71-L74
> Update block reward mock to match implementation

- contracts/mocks/AMBMock.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicForeignAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol
- test/amb_native_to_erc20/foreign_mediator.test.js
- test/arbitrary_message/foreign_bridge.test.js
- test/arbitrary_message/home_bridge.test.js
It was discovered, that it is not safe to allow passing messages while other message is currently processed. Specially formatted message can trigger an infinite loop, and eventually, all validators will burn their balance on gas expenses.
In order to fix this, the following restriction is introduced:
https://github.com/poanetwork/tokenbridge-contracts/blob/69c8f0bc94ff013d9317808076734a7a4feaf69a/contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol#L19-L20
This check will also make it impossible to bridge received fee in the same transaction, although it was possible to do so in the `AMB_NATIVE_TO_ERC` mode before.
> Fix infinite AMB message loop

- contracts/upgradeable_contracts/amb_native_to_erc20/BasicAMBNativeToErc20.sol
- contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol
- package-lock.json
- package.json
This version tag will contain the fix for the issue with imbalance of the native-to-erc20 AMB extension and an improvement to provide getters to get source and destination chain ids from AMB contract.
> Bump version to 5.0.2 before merging to master

- contracts/upgradeable_contracts/BasicAMBMediator.sol
- contracts/upgradeable_contracts/TokenBridgeMediator.sol
- contracts/upgradeable_contracts/amb_native_to_erc20/BasicAMBNativeToErc20.sol
- contracts/upgradeable_contracts/amb_native_to_erc20/HomeAMBNativeToErc20.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol
- contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol
- deploy/package-lock.json
- deploy/package.json
- deploy/src/amb_erc677_to_erc677/home.js
- deploy/src/arbitrary_message/foreign.js
- deploy/src/arbitrary_message/home.js
- deploy/src/erc_to_erc/home.js
- deploy/src/native_to_erc/foreign.js
- package-lock.json
- package.json
- test/amb_native_to_erc20/home_mediator.test.js
- test/arbitrary_message/foreign_bridge.test.js
- test/arbitrary_message/home_bridge.test.js
This updates provides a fix for a security issue addressed by
* [Fix] Use eth_chainId instead of net_version (#430), closes #431
* [Fix] Remove references to nonce (#434), closes #429
* [Fix] Make chain id getters public (#435), closes #428
* [Fix] Add missing call to setMediatorBalance (#436), closes #437
In order to bump the version the following PR was also merged:
* [Other] Bump version to 5.0.2 before merging to master (#438)
> Merge the develop branch to the master branch, preparation to v5.0.2

- package-lock.json
- package.json
This version tag will contain a new pair of the AMB mediators to provide ability to transfer an ERC20 token to the native coin similarly to the xDai bridge.
> Bump version to 5.1.0 before merging to master

- contracts/upgradeable_contracts/amb_erc20_to_native/BasicAMBErc20ToNative.sol
- contracts/upgradeable_contracts/amb_erc20_to_native/ForeignAMBErc20ToNative.sol
- contracts/upgradeable_contracts/amb_erc20_to_native/HomeAMBErc20ToNative.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/HomeStakeTokenMediator.sol
- contracts/upgradeable_contracts/amb_native_to_erc20/BasicAMBNativeToErc20.sol
- contracts/upgradeable_contracts/amb_native_to_erc20/ForeignAMBNativeToErc20.sol
- contracts/upgradeable_contracts/amb_native_to_erc20/HomeAMBNativeToErc20.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErc677ToErc677.sol
- contracts/upgradeable_contracts/erc20_to_erc20/ForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErcPOSDAO.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/native_to_erc20/ClassicHomeBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
It was found that static-sized arrays consume less bytes in ABI encoding than their dynamic versions.
Replacing some of the array parameters in initialization will definitely save some gas during deployment.
> Use uint256[N] instead of uint256[]

- contracts/PermittableToken.sol
- deploy/src/amb_erc677_to_erc677/home.js
- deploy/src/amb_native_to_erc20/foreign.js
- deploy/src/loadContracts.js
- deploy/src/utils/verifier.js
- flatten.sh
Closes #450 
This PR changes the behaviour of the deployment scripts as so the permittable token contract based on TokenBridge ERC677 implementation is used by default together with AMB mediators instead of the "vanilla" ERC677 token.
> Use permittable ERC677 token by default for AMB mediators

- contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol
Although the modification of the AMB contracts was made under `5.3.0` it did not modify any public available behaviour of the code. Anyway, in order to simplify the upgrade paths in the future it make sense to reflect in the contract version method that the source of the contracts was changed.
> Increase the version of AMB contracts to 5.3.0

- contracts/mocks/PermittableTokenMock.sol
- contracts/upgradeable_contracts/BasicAMBMediator.sol
- contracts/upgradeable_contracts/TokenBridgeMediator.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiTokenBridge.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeFeeManagerMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/MultiTokenBridgeMediator.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/callflows.md
- deploy/README.md
- deploy/src/loadEnv.js
- deploy/src/multi_amb_erc20_to_erc677/initializeForeign.js
- deploy/src/multi_amb_erc20_to_erc677/initializeHome.js
- test/multi_amb_erc20_to_erc677/foreign_mediator.test.js
- test/multi_amb_erc20_to_erc677/home_mediator.test.js
- test/poa20_test.js
After an additional discussion, it was decided to move fee manager functionality into the `HomeMultiAMBErc20ToErc677` mediator. Updated contracts bytecode size:
* **Home**: `22.7 kb`
* **Foreign**: `16.3 kb`
> Move fee manager into home mediator

- Dockerfile
- Dockerfile.dev
- docker-compose.yml
- package-lock.json
- package.json
Closes #350 
Created a new Dockerfile that only has the required files for deployment and upgrades. In this case, the contracts are built and flattened in a build step of docker so all the dependencies are removed except for the required by the deployment or upgrade scripts.
The previous Dockerfile was renamed to Dockerfile.dev so it can be used for development purposes like compiling the contracts, running the test, coverage, etc.
Sizes of the docker images:
- tokenbridge-contracts_dev: `1.72GB`
- **new** tokenbridge-contracts_bridge-contracts: `1.13GB`
> Create new Dockerfile for deployments/upgrades

- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol
Although the modifications of the AMB multi-token extension contracts were made under #466, they were not reflected in the version of the extension.
> Increase the version of AMB multi-token extension to 1.0.2

- CONTRIBUTING.md
- package-lock.json
- package.json
Fix some old links to the repository that left after the repo was renamed.
Relates to #312
> Update old repo references

- contracts/libraries/SafeERC20.sol
- contracts/upgradeable_contracts/amb_erc20_to_native/BasicAMBErc20ToNative.sol
- contracts/upgradeable_contracts/amb_erc20_to_native/ForeignAMBErc20ToNative.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/ForeignAMBErc677ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol
The proposed fix is to address the issue with tokens that does not revert for `transferFrom` and `transfer` calls and return `false` instead.
It is not possible to apply the approach suggested in https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0b489f4d79544ab9b870abe121077043feb971b8/contracts/token/ERC20/SafeERC20.sol#L64 due to significant rework required to switch to newer version of Solidity. Later it will be investigated a possibility to implement it in form of assembly.
> Extra check for balance increase

- package-lock.json
- package.json
This version contains the fix for AMB mediators to properly work with some non-standard ERC20 tokens and the changes for GitHub actions to publish flatten scripts
> Bump package version to 5.4.1

- contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol
A possible gas limit issue was identified in the AMB bridge contracts. Issue is related to the 63/64 rule for gas limit, introduced in the [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md). Please take a look at the commit diff for more information.
Bridge validator responsible for message delivery can intentionally or unintentionally use a raw value of `eth_estimateGas`, leading to the unexpected message failure with OOG error.
Such an issue can be only exploited when `maxGasPerTx()` in the contract is high enough (e. g. > `5000000`), so that 1/64 of this value will be enough to finish the function execution (at least 3 SSTORE (20000 gas) + 3 SSTORE (5000 gas)).
> Add extra check on internal call gaslimit

- contracts/upgradeable_contracts/BridgeValidators.sol
- contracts/upgradeable_contracts/OtherSideBridgeStorage.sol
- contracts/upgradeable_contracts/Ownable.sol
- contracts/upgradeable_contracts/RewardableValidators.sol
- contracts/upgradeable_contracts/amb_erc20_to_native/BasicAMBErc20ToNative.sol
- contracts/upgradeable_contracts/amb_erc677_to_erc677/BasicAMBErc677ToErc677.sol
- contracts/upgradeable_contracts/amb_native_to_erc20/BasicAMBNativeToErc20.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol
- contracts/upgradeable_contracts/erc20_to_erc20/BasicForeignBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/native_to_erc20/ForeignBridgeNativeToErc.sol
- contracts/upgradeable_contracts/native_to_erc20/HomeBridgeNativeToErc.sol
- test/amb_erc677_to_erc677/AMBErc677ToErc677Behavior.test.js
- test/arbitrary_message/foreign_bridge.test.js
- test/arbitrary_message/home_bridge.test.js
- test/native_to_erc/foreign_bridge_test.js
Some of the checks like `require(_owner != address(0))` were missing in a couple of contracts. This PR adds them where needed.
> Add missing zero address checks

- test/amb_erc677_to_erc677/foreign_bridge.test.js
This PR fixes a problem in tests which occurred after concurrent merges of #510 and #530
> Replace transfer calls by transferAndCall where needed

- contracts/upgradeable_contracts/ReentrancyGuard.sol
- contracts/upgradeable_contracts/arbitrary_message/MessageProcessor.sol
It was found that the Solidity compiler does not optimize the calculation of mapping storage slots in the cases where the slot remains constant. This PR refactors the code for temporary variables that are saved and removed from the storage within a single transaction. There are two benefits of such improvement:
* Transactions become cheaper, we are saving `~50` gas at each access operation to such variable by skipping redundant . For instance, usual Omnibridge withdraw operation contains 8 such accesses.
* Bytecode size decreases: AMB contracts bytecode decreased by `~300` bytes, mediators bytecode decreased by `~100` bytes each.
Also, worth noting that such optimizations can be also applied to other storage usages as well. For example, we can precalculate the exact storage slot of …
> Optimize use of temporary variables passed through storage

- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/ForeignMultiAMBErc20ToErc677.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/HomeMultiAMBErc20ToErc677.sol
This PR slightly reduces the gas usage for `bridgeSpecificActionsOnTokenTransfer` function in the MultiToken extension.
The following actions were performed:
* Remove unnecessary `abi.encodePacked(...)` call when dealing with `relayTokens` functionality.
* ~~Remove redundant `require(!lock());` check in `_relayTokens`, since the temporary lock variable cannot be set to `true` in the beginning of the `relayTokens` call.~~
* Remove redundant `lock()` check in `bridgeSpecificActionsOnTokenTransfer`, since the check was either already done previously in the code (in `onTokenTransfer`), or the lock was explicitly disabled by the call to `setLock(false)` (in `_relayTokens`).
> Optimize Omnibridge gas usage

- contracts/helpers/AMBBridgeHelper.sol
- contracts/helpers/Erc20ToNativeBridgeHelper.sol
- truffle-config.js
@k1rill-fedoseev has prepared two helpers which were deployed to xDai chain to help users manually collect signatures provided by the bridge oracles. The collected signatures are being used on another side of the bridge to execute the transfer.
> Helpers to collect signatures for erc20-to-native and AMB

- contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol
- contracts/upgradeable_contracts/multi_amb_erc20_to_erc677/BasicMultiAMBErc20ToErc677.sol
- package-lock.json
- package.json
Since [the code delta between `5.6.0` and `5.7.0-rc0`](https://github.com/poanetwork/tokenbridge-contracts/compare/5.6.0...1ae26c0ddefdc65cfdb41122919a43bdeb0605a2) contains the changes in AMB and OB contracts, the version tracking methods in the corresponding contracts were updated.
The package version was updated to be linked to the `5.7.0-rc0` release.
> Bump contracts and package version before 5.7.0-rc0

- contracts/upgradeable_contracts/VersionableBridge.sol
- package-lock.json
- package.json
Major of the bridge contracts was changed to `6.0.0` because the erc20-to-native contracts were reworked to support another scheme to earn interest
The package version was updated to be linked to the `5.7.0-rc1` release.
> Bump contracts and package version before 5.7.0-rc1

- package-lock.json
- package.json
The package major version is increased because the contracts for both bridge mode were significantly changed since the latest release (`5.6.0`).
> Bump package version before 6.0.0-rc0

- contracts/upgradeable_contracts/InterestReceiverStakeBuyback.sol
- contracts/upgradeable_contracts/InterestReceiverSwapToETH.sol
- contracts/upgradeable_contracts/erc20_to_native/CompoundConnector.sol
- contracts/upgradeable_contracts/erc20_to_native/InterestConnector.sol
The `InterestReceiverStakeBuyback` and `InterestReceiverSwapToETH` contracts both utilize Uniswap in order to swap tokens. There is some slippage protection, but no protection against price manipulation is built in.
Because the `payInterest` function in the `InterestConnector` is external and permissionless, anyone can call it at any time. Therefore, once enough interest accrues, one could take out a flash loan to manipulate the relevant Uniswap pools and call `payInterest` to make a profit.
Additionally, even if `payInterest` weren't permissionless, it is possible for the Uniswap call in `onInterestReceived` to fail, leaving the tokens sitting in the `InterestReceiver` contract. Here, the `onInterestReceived` function is external and permissionless, meaning it's once again prone to being …
> Stricter preconditions for payInterest

- contracts/libraries/Message.sol
The function parseMessage is preceded by a comment about the offsets of the different parts within the message. It contains:
https://github.com/poanetwork/tokenbridge-contracts/blob/b3511bf0987bbfef661e28dd1a6fbe1735f90ac0/contracts/libraries/Message.sol#L18
However the correct offset is 116. The code implements it correctly.
> Fix offset in comments

- contracts/mocks/XDaiForeignBridgeMock.sol
- contracts/upgradeable_contracts/GSNForeignERC20Bridge.sol
- contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol
- contracts/upgradeable_contracts/erc20_to_native/XDaiForeignBridge.sol
- deploy/src/erc_to_native/foreign.js
- deploy/src/loadContracts.js
- test/erc_to_native/foreign_bridge.test.js
- test/erc_to_native/foreign_bridge_gsn.test.js
When the `ForeignBridgeErcToNative` is used in Gas Station Network (GSN)-mode, token decimals are treated unevenly. Generally, as part of this report we assume that as only the DAI tokens is used in GSN mode, the token decimals will always be 18. And hence token decimals on foreign and home side will be the same.
However, the `ForeignBridgeErcToNative` will shift token amounts to account for different decimals when transferring tokens:
https://github.com/poanetwork/tokenbridge-contracts/blob/b3511bf0987bbfef661e28dd1a6fbe1735f90ac0/contracts/upgradeable_contracts/erc20_to_native/ForeignBridgeErcToNative.sol#L85-L86
Furthermore, sometimes the code does assume that token decimals are the same. As part of the `preRelayedCall` the `TokenPayMaster` estimates the value of the provided tokens by …
> Separate XDaiForeignBridge contract with compound and GSN support

- contracts/gsn/BasePaymaster.sol
- contracts/gsn/forwarder/IForwarder.sol
- contracts/gsn/interfaces/GsnTypes.sol
- contracts/gsn/interfaces/IPaymaster.sol
- contracts/gsn/token_paymaster/TokenPaymaster.sol
- contracts/upgradeable_contracts/GSNForeignERC20Bridge.sol
- package-lock.json
- package.json
- test/erc_to_native/foreign_bridge_gsn.test.js
The `postRelayedCall` function of the `TokenPaymaster` contract is public and allows anyone to call it. In this function the uniswap router is called and leftover funds are sent back to the user. Thus, this function modifies the state. Without an access control check that only allows the `RelayHub` to call it, an attacker can craft call data that will drain the ERC20 balance of the contract. Note that normally the contract is not supposed to have an ERC20 balance, however, this can change in situations as described in Anyone can steal GSN fees.
The `preRelayedCall` and `postRelayedCall` functions both have following comment in the official GSN `IPaymaster` class:
https://github.com/poanetwork/tokenbridge-contracts/blob/b3511bf0987bbfef661e28dd1a6fbe1735f90ac0/contracts/gsn/interfaces/IPaym …
> Update GSN interface

- contracts/upgradeable_contracts/VersionableBridge.sol
- contracts/upgradeable_contracts/arbitrary_message/VersionableAMB.sol
- package-lock.json
- package.json
The version has been updated to reflect the changes made for the latest security audit report under:
* #623 
* #624 
* #626
* #627
* #628
> Bump package and contracts interfaces version prior to 6.0.0-rc2

- contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol
- contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol
- test/arbitrary_message/foreign_bridge.test.js
In response to https://medium.com/immunefi/xdai-stake-arbitrary-call-method-bug-postmortem-f80a90ac56e3
> Block ERC20 selectors in AMB requests
